/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author saimh
 */
public class RegisterNew extends javax.swing.JFrame {
    ArrayList<Accounts> accounts;
    Accounts new_account;
    String account_no_generated;
    Random random = new Random();
    static int show_hide_pass = 1;
    
    /**
     * Creates new form RegisterNew
     */
    public RegisterNew() {
        initComponents();
        additionalPanel.setVisible(false);
        occupationList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Select", "National Forces", "Doctor", "Accountant", "Marketing & Brand Management", "Human Resource Management (HRM)", "IT" , "Others"}));
        accounts = new ArrayList<Accounts>();
        showPass.setIcon(new ImageIcon(getClass().getResource("hide.png")));
        showPass.setText("Show");
        //showPass.setSize(5, 5);
    }
    
    public String generateAccountNo(int max, int min){
        
        int randomNumber = random.ints(1, max, min).findFirst().getAsInt();
        account_no_generated = String.valueOf(randomNumber);
        return account_no_generated;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        married = new javax.swing.ButtonGroup();
        generateDialog = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        accountNoLabel = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        fatherName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        marriedY = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        spouseName = new javax.swing.JTextField();
        additionalCheckbox = new javax.swing.JCheckBox();
        additionalPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        zipcode = new javax.swing.JTextField();
        contactNo = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        occupationList = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        marriedN = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        generateButton = new javax.swing.JButton();
        accountNo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        generateButton1 = new javax.swing.JButton();
        showPass = new javax.swing.JButton();

        generateDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        generateDialog.setTitle("Generating Account no");
        generateDialog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        generateDialog.setResizable(false);

        jLabel15.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 153));
        jLabel15.setText("Account no is...");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/loading.gif"))); // NOI18N

        accountNoLabel.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        accountNoLabel.setForeground(new java.awt.Color(0, 153, 153));
        accountNoLabel.setText("Generating...");

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout generateDialogLayout = new javax.swing.GroupLayout(generateDialog.getContentPane());
        generateDialog.getContentPane().setLayout(generateDialogLayout);
        generateDialogLayout.setHorizontalGroup(
            generateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generateDialogLayout.createSequentialGroup()
                .addGroup(generateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, generateDialogLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(generateDialogLayout.createSequentialGroup()
                        .addGroup(generateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(generateDialogLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(accountNoLabel))
                            .addGroup(generateDialogLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel16)))
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addContainerGap())
        );
        generateDialogLayout.setVerticalGroup(
            generateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generateDialogLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(generateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(accountNoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("FILL OUT THE FOLLOWING");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Full Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Father Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Married:");

        married.add(marriedY);
        marriedY.setText("Yes");
        marriedY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marriedYActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Spouse Name:");
        jLabel5.setEnabled(false);

        spouseName.setEnabled(false);
        spouseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spouseNameActionPerformed(evt);
            }
        });

        additionalCheckbox.setText("Fill out Additional info now ? can be filled out later from Profile Settings");
        additionalCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additionalCheckboxActionPerformed(evt);
            }
        });

        additionalPanel.setBackground(new java.awt.Color(153, 204, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("ZipCode:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Contact No.");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Address:");

        occupationList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        occupationList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                occupationListActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Occupation:");

        javax.swing.GroupLayout additionalPanelLayout = new javax.swing.GroupLayout(additionalPanel);
        additionalPanel.setLayout(additionalPanelLayout);
        additionalPanelLayout.setHorizontalGroup(
            additionalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(additionalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(additionalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(additionalPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contactNo))
                    .addGroup(additionalPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(occupationList, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(additionalPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(address)))
                .addContainerGap())
        );
        additionalPanelLayout.setVerticalGroup(
            additionalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(additionalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(additionalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(zipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(contactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(additionalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(additionalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(occupationList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Email:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Password:");
        jLabel10.setToolTipText("Password Should be atleast 8 Characters Long");

        password.setToolTipText("Password Should be atleast 8 Characters Long");

        jButton1.setIcon(new javax.swing.ImageIcon("D:\\Projects\\NetBeansProjects\\Bank\\src\\pics\\save.png")); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        married.add(marriedN);
        marriedN.setText("No");
        marriedN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marriedNActionPerformed(evt);
            }
        });

        jLabel14.setText("Age:");

        generateButton.setText("Generate");
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });

        accountNo.setEditable(false);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Account No. (AutoFill)");

        generateButton1.setText("Suggest Password");
        generateButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButton1ActionPerformed(evt);
            }
        });

        showPass.setText("showPass");
        showPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(84, 84, 84))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(additionalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(additionalCheckbox, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                    .addComponent(age))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(marriedY)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(marriedN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spouseName)
                            .addComponent(fatherName))))
                .addGap(11, 11, 11))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(email)
                            .addComponent(password))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(generateButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(showPass)))
                        .addGap(65, 65, 65))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(accountNo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(generateButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(fatherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(marriedY)
                    .addComponent(jLabel5)
                    .addComponent(spouseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(marriedN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(additionalCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(additionalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(showPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(accountNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spouseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spouseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseNameActionPerformed

    private void marriedNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marriedNActionPerformed
        // TODO add your handling code here:
        if(marriedN.isSelected())
        {
            spouseName.setEnabled(false);
            jLabel5.setEnabled(false);
        }
    }//GEN-LAST:event_marriedNActionPerformed

    private void marriedYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marriedYActionPerformed
        // TODO add your handling code here:
        if(marriedY.isSelected())
        {
            spouseName.setEnabled(true);
            jLabel5.setEnabled(true);
        }
    }//GEN-LAST:event_marriedYActionPerformed

    private void additionalCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additionalCheckboxActionPerformed
        // TODO add your handling code here:
        if(additionalCheckbox.isSelected())
        {
            additionalPanel.setVisible(true);
        }
        else
        {
            additionalPanel.setVisible(false);
        }
    }//GEN-LAST:event_additionalCheckboxActionPerformed

    private void occupationListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_occupationListActionPerformed
        // TODO add your handling code here:
        if(occupationList.getSelectedIndex() == 0)
        {
            JOptionPane.showMessageDialog(null, "Make Valid Selection");
        }
    }//GEN-LAST:event_occupationListActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String user_name = "";
        String user_fatherName = "";
        int user_age = 0;
        Boolean user_married = false;
        String user_spouseName = "";
        String user_zipcode = "";
        String user_contact = "";
        String user_address = "";
        String user_occupation = "";
        String user_accountNo = "";
        String user_email = "";
        String user_password = "";
        if(name.getText().isEmpty() ||
           fatherName.getText().isEmpty() ||
           email.getText().isEmpty() || password.getPassword().length == 0 ||
           accountNo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Fill all the Fields!");
        }
        else
        {
            if(password.getPassword().length <= 8)
            {
                JOptionPane.showMessageDialog(null, "Password length should be greater than 8");
            }
            else
            {
                user_name = name.getText().trim();
                user_fatherName = fatherName.getText().trim();
                user_age = Integer.parseInt(age.getText().trim());
                user_accountNo = accountNo.getText().trim();
                        
                if(marriedY.isSelected()){
                    user_married = true;
                    user_spouseName = spouseName.getText().trim();
                    
                }
                else{
                    user_married = false;
                    user_spouseName = "N/A";
                }
                if(additionalCheckbox.isSelected()){
                    user_zipcode = zipcode.getText().trim();
                    user_contact = contactNo.getText().trim();
                    user_occupation = occupationList.getSelectedItem().toString();
                }
                else{
                    user_zipcode = "N/A";
                    user_contact = "N/A";
                    user_occupation = "N/A";
                }
                user_email = email.getText().trim();
                user_password = password.getPassword().toString();
                if(spouseName.getText().isEmpty() && marriedY.isSelected()){
                    JOptionPane.showMessageDialog(null, "Enter Spouse Name");
                }else if(additionalCheckbox.isSelected() && occupationList.getSelectedIndex() == 0){
                    JOptionPane.showMessageDialog(null, "Make Valid Selection in Occupation");
                }
                else{
                    JOptionPane.showMessageDialog(null, "Successful");
                    this.dispose();
                    new_account = new Accounts(user_name, user_fatherName, user_age, user_married, user_spouseName, user_address, user_zipcode, user_contact, user_accountNo, user_email, user_password);
                }
            }
        }     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        // TODO add your handling code here:
        generateDialog.setSize(400, 150);
        generateDialog.setVisible(true);
        accountNoLabel.setText("Generating...");
        jLabel16.setVisible(true);
        jButton2.setVisible(false);
        int delay = 2000;
        Timer timer = new Timer(delay, e ->{
            generateAccountNo(111111111, 999999999);
            jLabel16.setVisible(false);
            accountNoLabel.setText(account_no_generated);
            jButton2.setVisible(true);
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_generateButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        generateDialog.dispose();
        generateButton.setEnabled(false);
        generateButton.setText("Wait a bit");
        accountNo.setText(account_no_generated);
        int delay = 3000;
        Timer timer = new Timer(delay, e ->{
            generateButton.setEnabled(true);
            generateButton.setText("Generate");
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void generateButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generateButton1ActionPerformed

    private void showPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassActionPerformed
        // TODO add your handling code here:
        if(show_hide_pass == 1){
            showPass.setIcon(new ImageIcon(getClass().getResource("show.png")));
            showPass.setText("Hide");
            password.setEchoChar((char)0);
            show_hide_pass++;
        }else{
            showPass.setIcon(new ImageIcon(getClass().getResource("hide.png")));
            showPass.setText("Show");
            password.setEchoChar('*');
            show_hide_pass = 1;
        }
        
    }//GEN-LAST:event_showPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterNew().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountNo;
    private javax.swing.JLabel accountNoLabel;
    private javax.swing.JCheckBox additionalCheckbox;
    private javax.swing.JPanel additionalPanel;
    private javax.swing.JTextField address;
    private javax.swing.JTextField age;
    private javax.swing.JTextField contactNo;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fatherName;
    private javax.swing.JButton generateButton;
    private javax.swing.JButton generateButton1;
    private javax.swing.JDialog generateDialog;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.ButtonGroup married;
    private javax.swing.JRadioButton marriedN;
    private javax.swing.JRadioButton marriedY;
    private javax.swing.JTextField name;
    private javax.swing.JComboBox<String> occupationList;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton showPass;
    private javax.swing.JTextField spouseName;
    private javax.swing.JTextField zipcode;
    // End of variables declaration//GEN-END:variables
}
